name: "Enviar notificación por telegram"
description: "Envía una notificación por telegram sobre el resultado del workflow"
author: "Jordi Belda"
inputs:
  token:
    description: "Token del bot de Telegram"
    required: true
  id:
    description: "Id del usuario de Telegram"
    required: true

  workflow_name:
    description: "Nombre del workflow"
    required: true
    
  linter_result:
    description: "Resultado del linter_job"
    required: true
  cypress_result:
    description: "Resultado del cypress_job"
    required: true
  add_badge_result:
    description: "Resultado del add_badge_job"
    required: true
  deploy_result:
    description: "Resultado del deploy_job"
    required: true
outputs:
  status:
    description: "Estado del envío del correo"
runs:
  using: "node20"
  main: "dist/index.js"
