name: "Update README Badge"
description: "Modifica el README.md agregando un badge según el resultado de los tests"
author: "Jordi Belda"
inputs:
  test_result:
    description: "Resultado de los tests (success o failure)"
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
