name: main_workflow
on: push

jobs:
  linter-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: "actions/checkout@v4"

      - name: Configura Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Instal·la les dependencies
        run: npm install

      - name: Linter
        uses: "github/super-linter@v4"

    env:
      DEFAULT_BRANCH: main
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      LINTER_RULES_PATH: /
      JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
      VALIDATE_JAVASCRIPT_ES: true

  cypress-job:
    runs-on: ubuntu-latest
    #needs: linter-job

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configura Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: "http://localhost:3000"
          browser: chrome
          publish-summary: true
          summary-title: "Cypress Test Results"
        continue-on-error: true

      - name: Guardar resultado del job en result.txt
        run: |
          mkdir -p artifacts 
          if [ "${{ job.status }}" == "success" ]; then
            echo "success" > artifacts/result.txt
          else
            echo "failure" > artifacts/result.txt
          fi

      - name: Pujar artifact
        uses: actions/upload-artifact@v4
        with:
          name: cypress-summary
          path: artifacts/result.txt

  add_badge_job:
    runs-on: ubuntu-latest
    needs: cypress-job

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN_BADGE }}

      - name: Recuperar artifact de Cypress
        uses: actions/download-artifact@v4
        with:
          name: cypress-summary
          path: .

      # - name: Generar output a partir del resultat
      #   run: |
      #     CYPRESS_OUTCOME=$(cat result.txt)
      #     id: generate-output

      - name: Actualizar README.md amb el badge
        uses: ./.github/workflows/actions/update-badge
        with:
          test_result: ${{needs.cypress-job.result}}

      - name: Publicar canvis en el README.md
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          author_name: "Jordi Belda"
          author_email: "j.belda@test.com"
          message: "Actualiza el readme"
          push: true
          token: ${{secrets.TOKEN_BADGE}}

  deploy-job:
    runs-on: ubuntu-latest
    needs: cypress-job

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Token d'autenticació a Vercel
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # ID de l'organització a Vercel
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # ID del projecte a Vercel
          working-directory: .

  notification-job:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - linter_job
      - cypress_job
      - add_badge_job
      - deploy_job
    steps:
      - name: Send Notification
        uses: ./.github/workflows/actions/notification-job
        with:
          mailgun_api_key: ${{ secrets.MAIL_KEY }}
          recipient_email: ${{ secrets.RECIPIENT_EMAIL }}
          workflow_status: ${{ job.status }}
          workflow_name: ${{ github.workflow }}
          linter_result: ${{ needs.linter_job.result }}
          cypress_result: ${{ needs.cypress_job.result }}
          add_badge_result: ${{ needs.add_badge_job.result }}
          deploy_result: ${{ needs.deploy_job.result }}
